/*
 * This source file was generated by the Gradle 'init' task
 */
package entregasemana3;

public class App {
    public String getGreeting() {
        return "prueba compilacion";
    }

    public static void main(String[] args) {

    }
}
