/*
 * This source file was generated by the Gradle 'init' task
 */
package entregasemana3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

//Destinada a pruebas de Metodos

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
